# Generated by Django 4.2.6 on 2023-11-21 17:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import geces.core.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("city", models.CharField(max_length=255, verbose_name="Cidade")),
                ("address", models.CharField(max_length=255, verbose_name="Endereço")),
                ("zip_code", models.CharField(max_length=8, verbose_name="CEP")),
                ("phone", models.CharField(max_length=100, verbose_name="Telefone")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
        ),
        migrations.CreateModel(
            name="Responsible",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("email", models.EmailField(max_length=100, unique=True, verbose_name="E-mail")),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Masculino"), ("FEMALE", "Feminino")], max_length=50, verbose_name="Gênero"
                    ),
                ),
                ("birth", models.DateField(verbose_name="Nascimento")),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="people.address", verbose_name="Endereço"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsável",
                "verbose_name_plural": "Responsáveis",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("email", models.EmailField(max_length=100, unique=True, verbose_name="E-mail")),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Masculino"), ("FEMALE", "Feminino")], max_length=50, verbose_name="Gênero"
                    ),
                ),
                ("birth", models.DateField(verbose_name="Nascimento")),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="people.address", verbose_name="Endereço"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
            },
        ),
        migrations.CreateModel(
            name="Suplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("email", models.EmailField(max_length=100, unique=True, verbose_name="E-mail")),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Masculino"), ("FEMALE", "Feminino")], max_length=50, verbose_name="Gênero"
                    ),
                ),
                ("birth", models.DateField(verbose_name="Nascimento")),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="people.address", verbose_name="Endereço"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("email", models.EmailField(max_length=100, unique=True, verbose_name="E-mail")),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Masculino"), ("FEMALE", "Feminino")], max_length=50, verbose_name="Gênero"
                    ),
                ),
                ("birth", models.DateField(verbose_name="Nascimento")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Pendente"), (2, "Matriculado"), (3, "Cursando")],
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="Situação",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Saldo")),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="people.address", verbose_name="Endereço"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "responsible_student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_student",
                        to="people.responsible",
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discente",
                "verbose_name_plural": "Discentes",
            },
        ),
    ]
