# Generated by Django 4.2.6 on 2023-11-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="responsible_student",
        ),
        migrations.AddField(
            model_name="student",
            name="responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="people.responsible",
                verbose_name="Responsável",
            ),
        ),
    ]
