# Generated by Django 4.2.6 on 2023-11-27 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geces.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="created_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="updated_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="suplier",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="people.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AddField(
            model_name="suplier",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="created_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="suplier",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="updated_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="people.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="created_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="people.responsible",
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="updated_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="responsible",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="people.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AddField(
            model_name="responsible",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="created_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="responsible",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="updated_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="created_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="updated_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
    ]
