# Generated by Django 4.2.6 on 2023-11-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_remove_student_responsible_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsible",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="people.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="people.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="Saldo"),
        ),
        migrations.AlterField(
            model_name="suplier",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="people.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="people.address",
                verbose_name="Endereço",
            ),
        ),
    ]
