# Generated by Django 4.2.6 on 2023-11-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=100, unique=True, verbose_name="E-mail"),
        ),
    ]
