# Generated by Django 4.2.6 on 2023-12-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsible",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_related",
                to="people.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_related",
                to="people.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AlterField(
            model_name="suplier",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_related",
                to="people.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_related",
                to="people.address",
                verbose_name="Endereço",
            ),
        ),
    ]
