# Generated by Django 4.2.6 on 2023-11-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="phone",
        ),
        migrations.AddField(
            model_name="person",
            name="birth",
            field=models.DateField(default="2023-11-21", verbose_name="Nascimento"),
            preserve_default=False,
        ),
    ]
