# Generated by Django 4.2.6 on 2023-11-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_studentgroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="serie",
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="students",
            field=models.ManyToManyField(related_name="student_group", to="people.student", verbose_name="Discentes"),
        ),
    ]
