# Generated by Django 4.2.6 on 2023-11-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_remove_address_phone_person_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="phone",
        ),
        migrations.AddField(
            model_name="address",
            name="phone",
            field=models.CharField(default="", max_length=100, verbose_name="Telefone"),
            preserve_default=False,
        ),
    ]
