# Generated by Django 4.2.6 on 2023-11-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_remove_student_serie_alter_studentgroup_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="country_state",
        ),
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Masculino"), ("FEMALE", "Feminino")],
                default=1,
                max_length=50,
                verbose_name="Gênero",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(max_length=100, verbose_name="Telefone"),
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
