# Generated by Django 4.2.6 on 2023-12-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0005_alter_responsible_address_alter_student_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=10, verbose_name="CEP"),
        ),
    ]
