# Generated by Django 4.2.6 on 2023-12-05 12:18

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0006_alter_address_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsible",
            name="cpf",
            field=cpf_field.models.CPFField(max_length=14, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="student",
            name="cpf",
            field=cpf_field.models.CPFField(max_length=14, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="suplier",
            name="cpf",
            field=cpf_field.models.CPFField(max_length=14, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="cpf",
            field=cpf_field.models.CPFField(max_length=14, verbose_name="CPF"),
        ),
    ]
