# Generated by Django 4.2.6 on 2023-12-18 22:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import geces.core.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0008_rename_teacher_serie_teachers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "PENDING"), (2, "PAID"), (3, "CANCELLED")],
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Situação",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "MONTHLY"), (2, "OTHER")],
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Tipo",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Valor")),
                ("due_date", models.DateField(verbose_name="Data de Vencimento")),
                ("observations", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="academics.enrollment"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura",
                "verbose_name_plural": "Faturas",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            (1, "Dinheiro"),
                            (2, "Cartão de Crédito"),
                            (3, "Cartão de Débito"),
                            (4, "Boleto"),
                            (5, "PIX"),
                        ],
                        default=1,
                        max_length=50,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Valor")),
                ("discount", models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Desconto")),
                ("observations", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="finance.invoice"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
            },
        ),
    ]
