MAX_CHAR_FIELD_NAME_LENGTH = 255
MEDIUM_CHAR_FIELD_NAME_LENGTH = 100
SMALL_CHAR_FIELD_NAME_LENGTH = 50
PUBLIC_STRING = "PUBLIC"
PRIVATE_STRING = "PRIVATE"
DEFAULT_PAGE_SIZE = 10
MONTHLY_VALUE = 350
MONTHLY_DUE_DAY = 5
