# Generated by Django 4.2.6 on 2023-11-27 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Código")),
                ("enrollment_date", models.DateField(auto_now_add=True, verbose_name="Data de Matrícula")),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
            },
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Série",
                "verbose_name_plural": "Séries",
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
            },
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Código")),
                ("reference_year", models.PositiveSmallIntegerField(verbose_name="Ano referência")),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
            },
        ),
    ]
