# Generated by Django 4.2.6 on 2023-11-27 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geces.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="created_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="serie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_groups",
                to="academics.serie",
                verbose_name="Série",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="students",
            field=models.ManyToManyField(
                related_name="student_groups",
                through="academics.Enrollment",
                to="people.student",
                verbose_name="Discentes",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="updated_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="created_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="updated_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="created_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="series",
                to="academics.shift",
                verbose_name="Turno",
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="series",
                to="people.teacher",
                verbose_name="Professor",
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="updated_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="created_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="people.student"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student_group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academics.studentgroup"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(geces.core.models.get_sentinel_user),
                related_name="updated_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
    ]
