# Generated by Django 4.2.6 on 2023-11-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_initial"),
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="serie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="academics.serie",
                verbose_name="Série",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="people.student",
                verbose_name="Discente",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.studentgroup",
                verbose_name="Turma",
            ),
        ),
    ]
