# Generated by Django 4.2.6 on 2023-11-14 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serie",
            name="reference_year",
        ),
        migrations.RemoveField(
            model_name="serie",
            name="shift",
        ),
    ]
