# Generated by Django 4.2.6 on 2023-11-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_alter_studentgroup_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serie",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="series",
                to="academics.shift",
                verbose_name="Turno",
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="serie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_groups",
                to="academics.serie",
                verbose_name="Série",
            ),
        ),
    ]
