# Generated by Django 4.2.6 on 2023-11-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_alter_serie_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serie",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nome"),
        ),
    ]
