# Generated by Django 4.2.6 on 2023-11-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_alter_serie_shift_alter_studentgroup_serie"),
    ]

    operations = [
        migrations.AddField(
            model_name="serie",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Código"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shift",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Código"),
            preserve_default=False,
        ),
    ]
