# Generated by Django 4.2.6 on 2023-11-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_initial"),
        ("academics", "0004_alter_serie_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serie",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="series",
                to="people.teacher",
                verbose_name="Professor",
            ),
        ),
    ]
