# Generated by Django 4.2.6 on 2023-12-05 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0005_enrollment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Ativa"), (2, "Cancelada"), (3, "Pendente"), (4, "Trancada"), (5, "Concluída")],
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                verbose_name="Situação",
            ),
        ),
    ]
