# Generated by Django 4.2.6 on 2023-12-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0008_alter_student_status"),
        ("academics", "0006_alter_enrollment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serie",
            name="teacher",
        ),
        migrations.AddField(
            model_name="serie",
            name="teacher",
            field=models.ManyToManyField(related_name="series", to="people.teacher", verbose_name="Docente"),
        ),
    ]
