# Generated by Django 4.2.6 on 2023-12-11 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0007_remove_serie_teacher_serie_teacher"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serie",
            old_name="teacher",
            new_name="teachers",
        ),
    ]
