# Generated by Django 4.2.6 on 2023-11-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_alter_responsible_address_alter_student_address_and_more"),
        ("movement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpurchase",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_purchases",
                to="movement.product",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="productpurchase",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_purchases",
                to="movement.purchase",
                verbose_name="Compra",
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="sells",
                through="movement.ProductSell",
                to="movement.product",
                verbose_name="Produtos",
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sells",
                to="people.student",
                verbose_name="Estudante",
            ),
        ),
    ]
