# Generated by Django 4.2.6 on 2023-12-18 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import geces.core.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0008_alter_student_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("price", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Preço")),
                ("stock", models.IntegerField(default=0, verbose_name="Estoque")),
                ("image", models.ImageField(blank=True, null=True, upload_to="ProductImages")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.CreateModel(
            name="ProductPurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(default=0, verbose_name="Quantidade")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_purchases",
                        to="canteen.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto Compra",
                "verbose_name_plural": "Produtos Compras",
            },
        ),
        migrations.CreateModel(
            name="ProductSell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(default=0, verbose_name="Quantidade")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_sell",
                        to="canteen.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto Venda",
                "verbose_name_plural": "Produtos Vendas",
            },
        ),
        migrations.CreateModel(
            name="Sell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Pendente"), (2, "Pago"), (3, "Cancelado")],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sells",
                        through="canteen.ProductSell",
                        to="canteen.product",
                        verbose_name="Produtos",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sells",
                        to="people.student",
                        verbose_name="Estudante",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Pendente"), (2, "Pago"), (3, "Cancelado")],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compras",
                        through="canteen.ProductPurchase",
                        to="canteen.product",
                        verbose_name="Produtos",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to="people.suplier",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(geces.core.models.get_sentinel_user),
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
            },
        ),
        migrations.AddField(
            model_name="productsell",
            name="sell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_sell",
                to="canteen.sell",
                verbose_name="Venda",
            ),
        ),
        migrations.AddField(
            model_name="productpurchase",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_purchases",
                to="canteen.purchase",
                verbose_name="Compra",
            ),
        ),
    ]
